<?php

/**
 * This file is part of the Liquid package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package Liquid
 */

namespace Liquid\Tag;

use Liquid\AbstractTag;
use Liquid\Constant;
use Liquid\Exceptions\SyntaxError;
use Liquid\LiquidCompiler;
use Liquid\LiquidException;
use Liquid\Regexp;
use Liquid\Context;
use Liquid\Tokens\TagToken;
use Liquid\Traits\HelpersTrait;
use Liquid\Variable;
use ReflectionException;

/**
 * Performs an assignment of one variable to another
 *
 * Example:
 *
 *     {% assign var = var %}
 *     {% assign var = "hello" | upcase %}
 */
class TagAssign extends AbstractTag
{

    use HelpersTrait;

    /**
     * @var string The variable to assign from
     */
    private $from;

    /**
     * @var string The variable to assign to
     */
    private $to;

    /**
     * @var array
     */
    private $filters = [];

    /**
     * Constructor
     *
     * @param string $markup
     *
     * @param array|null $tokens
     * @param TagToken $token
     * @param LiquidCompiler|null $compiler
     * @throws SyntaxError
     */
    public function __construct($markup, array &$tokens, $token, LiquidCompiler $compiler = null)
    {
        parent::__construct(null, $tokens, $token, $compiler);

        $syntaxRegexp = new Regexp('/(' . Constant::VariableSignaturePartial . '+)\s*=\s*(' . Constant::QuotedFragmentPartial . ')\s*/ms');
        if($syntaxRegexp->match($markup)) {
            $this->to = $syntaxRegexp->matches[1];
            $this->from = $syntaxRegexp->matches[2];
        } else {
            throw new SyntaxError("Syntax Error in 'assign' - Valid syntax: assign [var] = [source]", $token);
        }

        $this->filters = (new Variable($markup, $compiler))->getFilters();
    }

    /**
     * Parses the given tokens
     *
     * @param array $tokens
     *
     * @return void
     * @throws SyntaxError
     */
    public function parse(array &$tokens)
    {
        if(in_array($this->to, Variable::getProtectedVariables())) {
            throw new SyntaxError(sprintf('Variable "%s" is protected!', $this->to), $this->getTagToken());
        }

        parent::parse($tokens); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the tag
     *
     * @param Context $context
     *
     * @return string|void
     * @throws LiquidException
     * @throws SyntaxError
     */
    public function render(Context $context)
    {
        $context->setToken($this->getTagToken());

        $output = $context->get($this->from);

        foreach (array_merge($this->globalFilters, $this->filters) as $filter) {
            list($filtername, $filterArgKeys) = $filter;

            $filterArgValues = array();

            foreach ($filterArgKeys as $arg_key) {
                $filterArgValues[] = $context->get($arg_key);
            }

            $output = $context->invoke($filtername, $output, $filterArgValues);
        }

        $context->set($this->to, $output, true);
    }

}
